### ISSUE TITLE
.env file not found

### ISSUE THREAD

**Issue by budarin** [joshgeller/react-redux-jwt-auth-example#14]
there is an error

**Comment by joshgeller** [comment]
Needs more info

**Comment by nickersonr** [comment]
I know this is far after the fact, but here is the "more info":

```
➜  workspace: git clone https://github.com/joshgeller/react-redux-jwt-auth-example.git
➜  workspace: cd react-redux-jwt-auth-example
➜  react-redux-jwt-auth-example git:(master): npm install
...
➜  react-redux-jwt-auth-example git:(master): export NODE_ENV=development
➜  react-redux-jwt-auth-example git:(master): node server.js
{ Error: ENOENT: no such file or directory, open '.env'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.config (/Users/user/workspace/react-redux-jwt-auth-example/node_modules/dotenv/lib/main.js:30:37)
    at Object.<anonymous> (/Users/user/workspace/react-redux-jwt-auth-example/config/index.js:5:8)
    at Module._compile (module.js:571:32)
    at normalLoader (/Users/user/workspace/react-redux-jwt-auth-example/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/user/workspace/react-redux-jwt-auth-example/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
==> 🌎  Listening on port 3000. Open up http://localhost:3000/ in your browser.
webpack built 54cbad467471f8bcf70c in 5390ms
```

**Comment by landrail8** [comment]
Did you resolve this problem?

**Comment by budarin** [comment]
no, I stopped using it.
