### ISSUE TITLE
node server.js

### ISSUE THREAD

**Issue by zanjs** [joshgeller/react-redux-jwt-auth-example#2]
$ node server.js
module.js:339
    throw err;
    ^

Error: Cannot find module './build/webpack/undefined'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

**Comment by joshgeller** [comment]
@zanjs, did you install the required dependencies? Anyone else running into this issue?

**Comment by deorbit** [comment]
This occurs when NODE_ENV is not set. Try `export NODE_ENV=development` first.
