### ISSUE TITLE
Example fails on startup with Node 5.10

### ISSUE THREAD

**Issue by mojochao** [joshgeller/react-redux-jwt-auth-example#23]
After clean git clone and npm install, and running under Node 5.10, I receive the following error:

```
/Users/someguy/Projects/programming/Playground/react-redux-jwt-auth-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126
      if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
                           ^

TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (/Users/agooch/Projects/programming/Playground/react-redux-jwt-auth-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
    at OptionManager.addConfig (/Users/agooch/Projects/programming/Playground/react-redux-jwt-auth-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/agooch/Projects/programming/Playground/react-redux-jwt-auth-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/agooch/Projects/programming/Playground/react-redux-jwt-auth-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (/Users/agooch/Projects/programming/Playground/react-redux-jwt-auth-example/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/Users/agooch/Projects/programming/Playground/react-redux-jwt-auth-example/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/agooch/Projects/programming/Playground/react-redux-jwt-auth-example/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

Any ideas on what the problem is?  Is there a last known good version of Node where this example runs correctly?

Many thanks in advance!

**Comment by david1983** [comment]
Runs fine on LTS

**Comment by andrewsantarin** [comment]
@mojochao the example works on node.js v6.9.1 (Windows).
